### ISSUE TITLE
Docker client version 1.40 is too new. Maximum supported API version is 1.39

### ISSUE THREAD

**Issue by EndeavorYen** [ITRI-ICL-Peregrine/x-k8s#33]
Refer the issue of kubespray 
https://github.com/kubernetes-sigs/kubespray/issues/6160

The Docker API version is too new.

> fatal: [openness1]: FAILED! => {"attempts": 20, "changed": true, "cmd": ["/usr/bin/docker", "images"], "delta": "0:00:00.047308", "end": "2020-05-27 07:36:24.994311", "msg": "non-zero return code", "rc": 1, "start": "2020-05-27 07:36:24.947003", "stderr": "Error response from daemon: client version 1.40 is too new. Maximum supported API version is 1.39", "stderr_lines": ["Error response from daemon: client version 1.40 is too new. Maximum supported API version is 1.39"], "stdout": "", "stdout_lines": []}

The workaround solution is that :
`apt-get install -y --allow-downgrades docker-ce-cli=5:19.03.8~3-0~ubuntu-$(lsb_release -cs)`
To execute this command before the installation.

**Comment by EndeavorYen** [comment]
> fatal: [openness1]: FAILED! => {"attempts": 5, "changed": false, "msg": "Cannot have both the docker-py and docker python modules installed together as they use the same namespace and cause a corrupt installation. Please uninstall both packages, and re-install only the docker-py or docker python module. It is recommended to install the docker module if no support for Python 2.6 is required. Please note that simply uninstalling one of the modules can leave the other module in a broken state."}

After i applied 

1.  `apt-get install -y --allow-downgrades docker-ce-cli=5:19.03.8~3-0~ubuntu-$(lsb_release -cs)`
or
2.  Modified `roles/container-engine/docker/vars/ubuntu-amd64.yml` to :

> docker_package_info:
  pkg_mgr: apt
  pkgs:
    - name: "docker-ce-cli=5:19.03.8~3-0~ubuntu-{{ ansible_distribution_release|lower }}"
      force: yes
    - name: "{{ docker_versioned_pkg[docker_version | string] }}"
      force: yes

**Comment by mJace** [comment]
Currently, branch dev_1.4.2 is patched.
This issue will be closed once we move on to the latest version of kubespray.

**Comment by mJace** [comment]
Fixed in release v1.4.2
