### ISSUE TITLE
helm installation failure

### ISSUE THREAD

**Issue by mJace** [ITRI-ICL-Peregrine/x-k8s#38]
Due to the URL is no longer available. the helm client installation fails.
the detailed error log as followed.
![img_1647](https://user-images.githubusercontent.com/9836691/102962048-f2d13900-4520-11eb-8a54-92b239d4545e.jpg)

Currently I've fix this in branch 'master-hotfix-1223', by defining a stable helm repo.
The ultimate solution is to catch up with new version of kubespray.

https://stackoverflow.com/questions/61954440/how-to-resolve-https-kubernetes-charts-storage-googleapis-com-is-not-a-valid

**Comment by mJace** [comment]
@EndeavorYen

**Comment by EndeavorYen** [comment]
I see. I will follow this issue. Thanks

**Comment by JustinHuang402490** [comment]
Fix it in 6527588.
